### ISSUE TITLE
Still seeing ads

### ISSUE THREAD

**Issue by sujaldev** [Ewpratten/youtube_ad_blocklist#13]
I updated the hosts file on my router but still seeing ads on youtube

Its not a problem on my end because:
- Yes I tried rebooting the router
- I checked some of the domains in the list with dig it returns 0.0.0.0

**Comment by Ewpratten** [comment]
We know about this. The hosts list will not block all Youtube ads. Just most of them. Google tries very hard to stop lists like this from working by scrambling their domain names for ad hosting. The best you can do is find some more domains, and add 'em to the list.
