### ISSUE TITLE
Pi-Hole unbound

### ISSUE THREAD

**Issue by iLLiac4** [Ewpratten/youtube_ad_blocklist#20]
Hi.
Trying to parse this list into the pi-hole with unbound installed.
https://ewpratten.retrylife.ca/youtube_ad_blocklist/unbound.txt

Upstream dns server is 127.0.0.1#5335 in Pi-hole
After parsing it says in the log:
  [i] Target: https://ewpratten.retrylife.ca/youtube_ad_blocklist/unbound.txt
  [✓] Status: No changes detected
  [i] Analyzed 364 domains, 364 domains invalid!
      Sample of invalid domains:
      - 127.0.0.1"
      - 127.0.0.1"
      - 127.0.0.1"
      - 127.0.0.1"
      - 127.0.0.1"

**Comment by iam-py-test** [comment]
Can you try https://ewpratten.github.io/youtube_ad_blocklist/domains.txt?
The version you used is designed for your HOSTS file

**Comment by iLLiac4** [comment]
Ok. This one works.
