### ISSUE TITLE
Not working with DNS66?

### ISSUE THREAD

**Issue by embyveddii** [Ewpratten/youtube_ad_blocklist#22]
Hi, I'm using this for DNS66 on Android and it doesn't seem to be blocking youtube ads in my browser. Is there a specific one i should be using? (ipv4, ipv6, domains, etc?) or is the project not updated?

**Comment by Ewpratten** [comment]
This *should* work. I have never used that app though, so I do not know if it requires some custom rules or something. 

https://ewpratten.github.io/youtube_ad_blocklist/hosts.ipv4.txt
