### ISSUE TITLE
clients.l.google.com blocks the ability to interact with google drive files

### ISSUE THREAD

**Issue by coderfin** [Ewpratten/youtube_ad_blocklist#3]
I added the Pi-hole lists to my Pi-hole.  Afterwards I could not delete a file in my google drive until I whitelisted `clients.l.google.com`.  Any thoughts?

**Comment by ShengChangYang** [comment]
I encountered a similar issue.
I can't open a certain Google Dive page that was shared by other ones.

**Comment by Ewpratten** [comment]
That makes sense. Fixed
