### ISSUE TITLE
All 13 domains invailid?

### ISSUE THREAD

**Issue by Swagnoor19** [Ewpratten/youtube_ad_blocklist#5]
So i added the https://github.com/Ewpratten/youtube_ad_blocklist/blob/master/blocklist.txt blocklist to my unraid docker pihole adlists and it worked fine for a day. Then I updated the gravity again and now I see this under this blocklist: 
![Screenshot (102)](https://user-images.githubusercontent.com/38535944/124843094-232d7180-df5f-11eb-81fc-bdd5243fe7e0.png)

Anyone else having this issue?

**Comment by Ewpratten** [comment]
Looks like you grabbed the wrong link. Here is the correct one for pihole:

```
https://ewpratten.retrylife.ca/youtube_ad_blocklist/hosts.ipv4.txt
```
